version: '3'
services:
  web:
    build:
      context: ./docker/construct_web      # Dockerfile保存場所
      dockerfile: Dockerfile-web    # Dockerfileファイル名
    ports:
      - 80:80
    depends_on: 
      - app
      
  app:
    build:
      context: ./docker/construct_app      # Dockerfile保存場所
      dockerfile: Dockerfile-app    # Dockerfileファイル名
    ports:                          # ポート接続
      - 3000:3000
    links:
      - redis
    depends_on: 
      - redis
    volumes:                        # mount workdir
      - ./myapp:/src
    command: [sh, -c, npm install && npm start]

  redis:
    image: redis:latest
    hostname: redis
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379 

